### ISSUE TITLE
[REFACTOR] <Organize the reminders better>

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/friendlyreminderbot#45]
### Description

As reminders.txt gets longer and longer, I think it may become challenging to keep updating it.

What's the best way to organize it better?

Should we have sub-categories, for example?

**Comment by kiyan-h** [comment]
@ykdojo 

I was thinking of doing this before.

Instead of having one large category, we could break them down into smaller ones. 

For example, instead of having a general "Health" Category, we could break it down into "Hydration", "Exercise", "Sleep", etc.

Another way we could do it would be nested categories (subcategories). But I'm not sure how you would do that in a YAML-compatible file.

Either way I'm up to do it, just let me know which way you think it would work the best.

**Comment by ykdojo** [comment]
@the-k-cmd thank you!

Having subcategories might be the best approach here.

I was just looking at [this tutorial](https://rhnh.net/2011/01/31/yaml-tutorial/), and it looks like you can indent subcategories like this:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1811651/169622185-c8b99986-47c9-46e1-bb9a-ed8643a40cea.png">

So I'm guessing it might be ok to do something like:

```
Category 1:
    Subcategory 1:
    Subcategory 2:
        Reminder 1
        Reminder 2
```

I'm not 100% sure though. We might need to test that format to see if it works.

**Comment by kiyan-h** [comment]
Sure, on it 👍

**Comment by kiyan-h** [comment]
Hiya, @ykdojo, quick question

How would you categorize these two? 

![image](https://user-images.githubusercontent.com/99749209/169625933-82b38b41-9639-472c-8bf5-35a1d4a1352d.png)

I think they both fit into one category, maybe "Body Reminders"?
However the first one can also fit into "Screen-Time Reminders".

What do you think?

**Comment by ykdojo** [comment]
Yeah it is kinda tricky.

The first seems like a body reminder, maybe a "Bodily Reminder" (cause it kinda sounds funny to me haha)

The second one seems more like a mental health reminder?

**Comment by kiyan-h** [comment]
I agree, that's what I'll do

**Comment by ykdojo** [comment]
Sounds good! Thank you
